version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: testwebservice

    working_directory: ~/laravel

    steps:
      - checkout
      - run:
          name: Install PHP exts
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install pdo_mysql
            sudo apt install -y default-mysql-client
      - run: sudo composer self-update

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Setup Laravel stuffs
          command: |
            php artisan migrate --force
      - run: ./vendor/bin/phpunit

      #katalon
      - run:
          name: Execute Katalon Studio
          command: |
            chmod -R 755 ./Katalon_Studio_Linux_64-6.3.3
            sudo ./Katalon_Studio_Linux_64-6.3.3/katalon -noSplash -runMode=console -consoleLog -noExit -projectPath="./katalontc/libraryTest.prj" -retry=0 -testSuitePath="./katalontc/Test Suites/testRegisSuccess" -executionProfile="default" -browserType="Chrome"
      - store-test_results:
          path: ./Reports
      - store-artifacts:
          path: ./Reports
workflows:
  version: 2
  notify_deploy:
    jobs:
      - build